{{- if not .Values.multi_model }}
apiVersion: v1
kind: Service
metadata:
  name: vllm
  namespace: {{ .Values.namespace }}
  labels:
    app: vllm
spec:
  type: ClusterIP
  selector:
    app: vllm
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
{{- else }}
{{- range .Values.models }}
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-{{ .slug }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: vllm
    model: {{ .slug }}
spec:
  type: ClusterIP
  selector:
    app: vllm
    model: {{ .slug }}
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
{{- end }}
{{- end }}
